Update CONTRIBUTING.md
codeforcauseorg/edu-client pull request #126
Opened 2021-03-20 16:52 UTC by helloCodingEra

fixed issue number #124 

 corrected some grammatical errors

2021-03-21 07:32 UTC, Abhishek-kumar09 requested changes
Changes

2021-03-21 07:32 UTC, Abhishek-kumar09 commented on CONTRIBUTING.md
> +If it is not yet considered or something more can be added then please create a new issue in the GitHub repository[new-issue] describing your enhancement.
This is not looking good to me
![image](https://user-images.githubusercontent.com/48255244/111897303-3b779000-8a45-11eb-92f4-82eac1403643.png)

2021-03-21 07:32 UTC, Abhishek-kumar09 commented on CONTRIBUTING.md
> +Now you have made the changes , tested them, and built them so now its time to push them.
Remove space before comma.
Change it to:
Once you made the changes, and tests are successfully passing you can push your changes to remote.

2021-03-21 08:40 UTC, AvineshTripathi reviewed
I solved the problem with the hyperlink but couldn't find way to solve the space thing as if i delete the space it shows error

2021-03-22 21:09 UTC, Abhishek-kumar09 requested changes

2021-03-22 21:09 UTC, Abhishek-kumar09 commented on CONTRIBUTING.md
> +Firstly please refer to the applicable GitHub repository [github-repo] and search the repository's GitHub issues [issues-list] to make sure that your idea has not been (or is not still) considered.
Github repository is mentioned twice and issues is also written twice.
You can revert these changes

2021-03-22 21:09 UTC, Abhishek-kumar09 commented on CONTRIBUTING.md
> +Now you have made the changes , tested them, and built them so now its time to push them.
Change this sentence to : `Once you made the changes, and tests are successfully passing you can push your changes to remote.`

2021-03-24 18:47 UTC, merged