Fix: Typography
codeforcauseorg/edu-client pull request #142
Opened 2021-03-25 20:00 UTC by faisaljamil25

**Issue Number**

fixes #141 

**Describe the changes you've made**

Typography configuration has changed and font sizes are increased. Also fixed font sizes in some files.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

`NA`

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2021-03-26 11:10 UTC, faisaljamil25 commented
@Abhishek-kumar09 please review this and let me know any changes.

2021-03-26 17:23 UTC, Abhijay007 reviewed
![typo](https://user-images.githubusercontent.com/64387054/112669723-0d9bac80-8e86-11eb-82a9-c810ba1d9c04.gif)

@faisaljamil25 LGTM 👍

2021-03-26 18:06 UTC, Abhishek-kumar09 requested changes
The sizes are too big.
Also some fontweights are also changed.
e.g: 
[expected](https://user-images.githubusercontent.com/48255244/112674379-dfb96680-8e8b-11eb-9baa-ac97367726cb.png)
[Actual](https://user-images.githubusercontent.com/48255244/112674566-198a6d00-8e8c-11eb-8cad-81f5a82031ee.png)

2021-03-26 18:06 UTC, Abhishek-kumar09 commented on src/theme/typography.js
>      letterSpacing: "-0.24px",
The sizes are too big according to me. 
This is the the typography you can look to https://github.com/codeforcauseorg/codeforcause.org/blob/HEAD/src/theme/typography.js

2021-03-26 19:11 UTC, Abhishek-kumar09 commented
Please also share screenshots of pages

2021-03-26 19:34 UTC, faisaljamil25 commented
![Screenshot 2021-03-27 005642](https://user-images.githubusercontent.com/69186619/112683476-a129a900-8e97-11eb-9c02-b5a40e01912d.png)
![Screenshot 2021-03-27 005738](https://user-images.githubusercontent.com/69186619/112683490-a686f380-8e97-11eb-854b-a4f4bc0eef00.png)
![Screenshot 2021-03-27 005821](https://user-images.githubusercontent.com/69186619/112683498-a8e94d80-8e97-11eb-9dac-2ccafca67d2f.png)
![Screenshot 2021-03-27 005623](https://user-images.githubusercontent.com/69186619/112683509-ab4ba780-8e97-11eb-88b1-17919410117e.png)
![Screenshot 2021-03-27 005642](https://user-images.githubusercontent.com/69186619/112683517-ad156b00-8e97-11eb-9ff1-107fc6fcd7ed.png)

do I need to reduce the font size more?

2021-03-26 20:37 UTC, Abhishek-kumar09 requested changes

2021-03-26 20:37 UTC, Abhishek-kumar09 commented on src/theme/typography.js
> +    fontWeight: 500,
make it 600

2021-03-26 20:37 UTC, Abhishek-kumar09 commented on src/theme/typography.js
> +    fontWeight: 500,
600

2021-03-26 20:37 UTC, Abhishek-kumar09 commented on src/theme/typography.js
> +    fontWeight: 600,
700

2021-03-26 20:38 UTC, Abhishek-kumar09 commented
Make this a bit smaller and thicker 
![image](https://user-images.githubusercontent.com/48255244/112690124-4a28d180-8ea1-11eb-911d-f7cf433c86c7.png)

2021-03-26 20:39 UTC, Abhishek-kumar09 commented
The less there will be changes in current view of app, the better it would be

2021-03-26 22:05 UTC, faisaljamil25 commented
![Screenshot 2021-03-27 033204](https://user-images.githubusercontent.com/69186619/112697275-397e5880-8ead-11eb-804f-6f371109f443.png)
Does this look good?

2021-03-27 18:46 UTC, Abhishek-kumar09 commented
Hi @faisaljamil25 
This is the figma design: https://www.figma.com/file/3QxrkclcjQFa2dplfWrQ8v/CFC-Application-(Copy)

Please ensure the changes align with the design.

2021-03-27 19:09 UTC, faisaljamil25 commented
> Hi @faisaljamil25
> This is the figma design: https://www.figma.com/file/3QxrkclcjQFa2dplfWrQ8v/CFC-Application-(Copy)
> 
> Please ensure the changes align with the design.

@Abhishek-kumar09 I have almost made the typography and font sizes identical or near to the one that you have provided and also changed some places where font sizes and font weights are hardcoded but still, a lot of places are left to be redefined and it would take a whole lot of time to correct each place to make as identical with the design (say if I increase font-weight of h3 to make align at one place it may be possible that it breaks font style at some other place and then I have to go to those individual places to change their variants and who knows correcting that place font style may lead to change in font-weight of some other variant and the loop continues). So, I think it would be better if we define a common typography configuration and then change the font style while working on those files themselves. What do you think?

2021-03-28 07:04 UTC, faisaljamil25 commented
@Abhishek-kumar09 have a look at this:
![Screenshot 2021-03-28 123146](https://user-images.githubusercontent.com/69186619/112744928-d9c5a180-8fc1-11eb-8927-b36a4d9b3a77.png)
![Screenshot 2021-03-28 123223](https://user-images.githubusercontent.com/69186619/112744929-db8f6500-8fc1-11eb-9797-a4e2ab7f5d5d.png)

2021-03-28 07:35 UTC, Abhishek-kumar09 commented
Looks good, Thanks @faisaljamil25

2021-03-28 07:35 UTC, merged