Add Wishlist Icon in every course description
codeforcauseorg/edu-client pull request #299
Opened 2021-04-28 17:05 UTC by poojadas07

**Issue Number**

fixes #297 

**Describe the changes you've made**

https://user-images.githubusercontent.com/66192403/116444061-f7608200-a871-11eb-8455-63eeb1f09ffe.mp4

**Checklist**

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2021-04-29 04:32 UTC, poojadas07 commented
> **Issue Number**
> 
> fixes #297
> 
> **Checklist**
> 
> * [x]  My code follows the code style of this project.
> * [] My change requires a change to the documentation.
> * [] I have updated the documentation accordingly.
> * [x]  All new and existing tests passed.
> * [x]  The title of my pull request is a short description of the requested changes.

@Abhishek-kumar09 please check !!

2021-04-29 05:46 UTC, Abhishek-kumar09 requested changes
Please remove these empty files. 
Copy that package-lock.json from the main repo and paste it in your commit.

2021-04-30 03:43 UTC, poojadas07 commented
> Please remove these empty files.
> Copy that package-lock.json from the main repo and paste it in your commit.

Done......please review !!

2021-04-30 18:45 UTC, Abhishek-kumar09 approved these changes

2021-04-30 18:45 UTC, merged