feat: develop links & resources page
codeforcauseorg/edu-client pull request #311
Opened 2021-05-08 12:45 UTC by sakshi-choudhary

**ISSUE #310**

**Describe the changes you've made**

Developed a Links & Resources page.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**
I have rendered conditionally so if the link / doc does not have a preview image, it will be rendered without an image.

=

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route
 

<!-- Please add deployed link to here text >

**PREVIEW**

<img width="400" alt="Screenshot 2021-05-08 at 18 04 57" src="https://user-images.githubusercontent.com/66865329/117539679-5455f800-b029-11eb-9b5c-eed189bfd6f7.png">

2021-05-08 12:46 UTC, sakshi-choudhary commented
@Abhishek-kumar09 Please review!

2021-05-08 13:40 UTC, Abhishek-kumar09 commented
Give some more left and right margin.

2021-05-08 15:12 UTC, Abhijay007 reviewed
@sakshi-choudhary I reviewed your code and there are some minor changes that I want to suggest:

1. Instead of showing links and resources in a unordered format you can make a subsection for both like the upper one for "links" and the lower one for "resources" or downloadable material. means it looks more ordered and supervised to the user and provided a good user experience in my opinion. 

2. Avoid writing links as subtext like it looks good without them,  instead of showing links just show the name of the topic or Another thing you can do is to mention the site or source name as subtext.

these are just suggestions 😄. it is up to you if u want to implement these or not.

2021-05-08 15:55 UTC, sakshi-choudhary commented
> @sakshi-choudhary I reviewed your code and there are some minor changes that I want to suggest:
> 
> 1. Instead of showing links and resources in a unordered format you can make a subsection for both like the upper one for "links" and the lower one for "resources" or downloadable material. means it looks more ordered and supervised to the user and provided a good user experience in my opinion.
> 2. Avoid writing links as subtext like it looks good without them,  instead of showing links just show the name of the topic or Another thing you can do is to mention the site or source name as subtext.
> 
> these are just suggestions 😄. it is up to you if u want to implement these or not.

I think this doesn't make sense in separating the links, resource is a resource and I kept  full link text as well so that incase the link is not opening by clicking user can copy the link and open it in another tab.

2021-05-08 15:56 UTC, sakshi-choudhary commented
@Abhishek-kumar09 Please check now, I've given margin in -axis

2021-05-09 04:27 UTC, Abhijay007 commented
> I kept full link text as well so that incase the link is not opening by clicking user can copy the link and open it in another tab.

It is nice as you provide a "link address" to the user to use it in case the link is not working, but it is hard to copy that link because there is not an option to copy that link, and in mobile devices (as far as I know) long presses to copy text is not supported in Apps. You can add a option to copy the text on click or provide a clipboard icon with the same functionality.

2021-05-09 04:57 UTC, sakshi-choudhary commented
> > I kept full link text as well so that incase the link is not opening by clicking user can copy the link and open it in another tab.
> 
> It is nice as you provide a "link address" to the user to use it in case the link is not working, but it is hard to copy that link because there is not an option to copy that link, and in mobile devices (as far as I know) long presses to copy text is not supported in Apps. You can add a option to copy the text on click or provide a clipboard icon with the same functionality.

Yes, this will be convenient for users, I'll implement. Thanks :)

2021-05-09 05:05 UTC, sakshi-choudhary commented
@Abhishek-kumar09 I have implemented  `copy link to clipboard` feature as well. Please do a review!

2021-05-09 06:49 UTC, Abhishek-kumar09 requested changes

2021-05-09 06:49 UTC, Abhishek-kumar09 commented on src/pages/Resources /index.js
> +            <React.Fragment>
replace it with `<>`

2021-05-10 11:30 UTC, sakshi-choudhary commented
@Abhishek-kumar09 ping!

2021-05-10 11:33 UTC, Abhishek-kumar09 approved these changes

2021-05-10 11:33 UTC, merged