New navbar
codeforcauseorg/edu-client pull request #355
Opened 2021-06-07 10:51 UTC by ritik-vashist

fixes #346 

Updated user avatar in  navbar.

2021-06-07 10:58 UTC, ritik-vashist commented
@Abhishek-kumar09  Sir, this  is the new PR for the issue #346 and updated changes of #352.
I request you please check it once.

Screenshot after modifications are attached bellow.
![12](https://user-images.githubusercontent.com/66052961/121005387-64d6cb00-c7ad-11eb-8c9a-6cd8df2f7578.png)
![10](https://user-images.githubusercontent.com/66052961/121005397-6607f800-c7ad-11eb-89a0-feeb197d9d76.png)

2021-06-11 19:35 UTC, ritik-vashist commented
@vasudevsinghal , @Abhishek-kumar09 Sir, I request you to review my work and share your valuable feedback.

2021-06-11 21:58 UTC, Abhishek-kumar09 requested changes
Since there are no changes in `package.json` there must be no change in `package-lock.json`.

2021-06-11 21:58 UTC, Abhishek-kumar09 commented on src/components/NavBar/index.js
> +          )}
Remove this and put 
```js
<Avatar             
  className={classes.avatar}             
  src={`${user.photoURL}`}   
/>
```
under the condition above.
```jsx
<Typography  className={classes.title} variant="h6" noWrap>
           Hi, {user.displayName}            
</Typography>
```

2021-06-12 07:11 UTC, ritik-vashist commented
But @Abhishek-kumar09  Sir, it will be needed in mobile view to show code for cause logo when the user is not log-in.

2021-06-12 10:42 UTC, closed without merging