Add padding in wishlist container
codeforcauseorg/edu-client pull request #40
Opened 2021-03-11 17:14 UTC by rajatgupta24

**Issue Number**
fixes #37

**Describe the changes you've made**
Add extra padding in the end of wishlist container 

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2021-03-11 18:08 UTC, Abhishek-kumar09 requested changes

2021-03-11 18:08 UTC, Abhishek-kumar09 commented on src/layouts/MainLayout/index.js
> +import BottomNav from './BottomNav';
These changes are already merged, please rebase to latest master

2021-03-11 18:08 UTC, Abhishek-kumar09 commented on src/pages/wishListView/index.js
> +  },
This will add unessential extra padding to all the wishlist element, and the problem is not kimited to wishlist but also other pages

2021-03-11 18:08 UTC, Abhishek-kumar09 commented on src/layouts/MainLayout/BottomNav.js
> +}
Please revert this change

2021-03-11 18:09 UTC, Abhishek-kumar09 commented
Please revert changes in lock file, they are not the part of this PR

2021-03-11 18:13 UTC, Abhishek-kumar09 commented
The only thing you need to do is to change 
https://github.com/codeforcauseorg/edu-client/blob/8c48616c950a4a2875c79e4211d2e6373673dd79/src/layouts/MainLayout/index.js#L19

`paddingTop: 64` to `paddinBottom: 64`, This will solve the issue.

2021-03-12 06:23 UTC, Abhishek-kumar09 requested changes
Please remove all the other changes and just add changes which is done on line 19 of `MainLayout/index.js`. You have merge conflicts.

2021-03-12 06:23 UTC, Abhishek-kumar09 commented on src/layouts/MainLayout/index.js
> +    padding: "4rem 0"
Don't need top padding anymore, Just change it to have only bottom padding.

2021-03-12 07:20 UTC, rajatgupta24 commented
There is some error happening in my local repo can i create another PR.

2021-03-12 08:43 UTC, closed without merging