UI: Added Cards for Course Detail Page
codeforcauseorg/edu-client pull request #82
Opened 2021-03-13 18:55 UTC by rizwan2000rm

**Issue Number**

fixes #5

**Describe the changes you've made**

Added a Card Component for Course Detail Page, also added a wrapper container for horizontal scrolling list.

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

2021-03-13 18:59 UTC, rizwan2000rm commented
@Abhishek-kumar09 @KeenWarrior Please review this PR.

2021-03-13 19:03 UTC, Abhishek-kumar09 requested changes
No new package is added thus there should be no new changes in package-lock.json.

Please copy and paste the the lock file form main repo to revert these changes

2021-03-13 19:03 UTC, Abhishek-kumar09 commented on src/components/cardContainer/cardContainer.js
> +// import Container from "@material-ui/core/Container";
Delete this and remove extra newline

2021-03-13 20:57 UTC, rizwan2000rm commented on src/components/cardContainer/cardContainer.js
> +// import Container from "@material-ui/core/Container";
Done

2021-03-13 20:59 UTC, rizwan2000rm commented
@Abhishek-kumar09 I have copied the exact whole package-lock file from the repo's latest commit it still shows that it has been edited but has the exact same content now.

2021-03-19 06:49 UTC, KeenWarrior approved these changes

2021-03-19 06:49 UTC, merged